apiVersion : apps/v1
kind: Deployment
metadata:
  name: martandazureaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: martandazureaks 
    spec:
      containers:
        - name: martandazureaks 
          image: democontinerregistry.azurecr.io/martandazureaks
          ports:
          - containerPort: 8080
