kind: PersistentVolume
apiVersion: v1
metadata:
 name: mongo-pv
 namespace: hands-on
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/mongo_data"
    
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: mongo-pv-claim
 namespace: hands-on
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 1Gi
   
---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mongodb
#   namespace: hands-on
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mongodb
#   template:
#     metadata:
#       labels:
#         app: mongodb
#     spec:
#       containers:
#         - name: mongodb
#           image: mongo:3.6.9
#           ports:
#             - containerPort: 27017
#           resources:
#             limits:
#               memory: 200Mi
---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: task-pv-pod
# spec:
#   volumes:
#     - name: mongo-pv-storage
#       persistentVolumeClaim:
#         claimName: mongo-pv-claim
#   containers:
#     - name: mongodb
#       image: mongo:3.6.9
#       ports:
#         - containerPort: 27017
#       volumeMounts:
#         - mountPath: /data/db
#           name: mongo-pv-storage







apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: hands-on
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      #targetPort: 27017
  #clusterIP: None
  #selector:
     #app: mongodb
    
--- 
 
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: hands-on
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
       - name: mongo-pv-storage
         persistentVolumeClaim:
           claimName: mongo-pv-claim
      containers:
       - name: mongo
         image: mongo:3.6.9
         command:
          - mongod
          - "--bind_ip"
          - 0.0.0.0
          - "--smallfiles"
          - "--noprealloc"
         ports:
          - containerPort: 27017
         volumeMounts:
          - name: mongo-pv-storage
            mountPath: /data/db