apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: hands-on
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: pro
        image: democontinerregistry.azurecr.io/hands-on/product-service
        #imagePullPolicy: Never
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
#         envFrom:
#         - secretRef:
#             name: config-client-credentials
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
#         livenessProbe:
#           httpGet:
#             scheme: HTTP
#             path: /actuator/info
#             port: 8080
#           initialDelaySeconds: 10
#           periodSeconds: 10
#           timeoutSeconds: 2
#           failureThreshold: 20
#           successThreshold: 1
#         readinessProbe:
#           httpGet:
#             scheme: HTTP
#             path: /actuator/health
#             port: 8080
#           initialDelaySeconds: 10
#           periodSeconds: 10
#           timeoutSeconds: 2
#           failureThreshold: 3
#           successThreshold: 1
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product
  namespace: hands-on
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product
  targetCPUUtilizationPercentage: 70

---

apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: hands-on
spec:
  selector:
    app: product
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  #type: NodePort
